name: C/C++ CI

on:
  pull_request:
    types:
      - closed
  push:
    branches:
      - master
      - "feature/**"
      - "bugfix/**"
      - "release/**"

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v1
    - name: dependencies
      run: sudo apt-get install cmake make g++
    - name: prepare
      run: cmake .
    - name: compilation
      run: make
    - name: test cases
      run: ./run-tests
